language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libgeos-c1
install: 'pip install -r requirements.txt --use-mirrors'
script: nosetests
env:
    CLUSTERIT_SETTINGS_MODULE=tests.settings
branches:
    only:
        - master
        - develop
        - /^feature\/.*$/
        - /^hotfix\/.*$/
        - /^support\/.*$/

