language: python
python:
    - "2.7"
    - "3.3"
before_install:
    - echo "yes" | sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
    - sudo apt-get update -qq
    - sudo apt-get install -qq libgeos-c1 libgeos-dev
    - sudo apt-get install -qq postgresql-9.1-postgis-2.0
before_script:
   - psql -c 'CREATE DATABASE test_clusterit;' -U postgres
   - psql -d test_clusterit -c "CREATE EXTENSION postgis;" -U postgres
install: 'pip install -r requirements.txt --use-mirrors'
script: nosetests
env:
    CLUSTERIT_SETTINGS_MODULE=tests.settings
branches:
    only:
        - master
        - develop
        - /^feature\/.*$/
        - /^hotfix\/.*$/
        - /^support\/.*$/

